// <auto-generated />
namespace TgiApplications.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _AddAmountToOfflineOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_AddAmountToOfflineOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202112220609388__AddAmountToOfflineOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
